name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.runs-on }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
        runs-on:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - name: Test
        run: |
          bundle exec rake
      - name: Test with REXML
        run: |
          bundle exec rake
        env:
          CHUPA_TEXT_SAX_PARSER_BACKEND: rexml
